---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
    - name: install EPEL repo
      package: name=epel-release state=present
    - name: install python-pip
      yum: name=python-pip state=present update_cache=yes
    - name: install docker python
      pip: name=docker-py
  tasks:
  - name: create apache conteneur
    docker_container:
      name: webapp
      image: httpd
      ports:
        - "80:80"
